# Generated by Django 4.2.5 on 2023-09-21 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManterAreas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_areas', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ManterCidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ManterCursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_curso', models.CharField(max_length=100)),
                ('carga_horaria_total', models.CharField(max_length=100)),
                ('duracao_meses', models.CharField(max_length=100)),
                ('area_saber_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.manterareas')),
            ],
        ),
        migrations.CreateModel(
            name='ManterDiciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_diciplina', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ManterEnsino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_ensino', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=50)),
                ('site', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ManterOcupacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_ocupacao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='manterSemestres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_semestre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ManterTurmas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_turma', models.CharField(max_length=100)),
                ('periodo_semestre_turma', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TiposAvaliacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tipo_avaliacao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ManterPessoas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pessoa', models.CharField(max_length=50)),
                ('pai', models.CharField(max_length=50)),
                ('mae', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=50)),
                ('data_nasc', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('cidade_pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mantercidade')),
                ('ocupacao_pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.manterocupacao')),
            ],
        ),
        migrations.CreateModel(
            name='ManterMatriculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio_matricula', models.CharField(max_length=20)),
                ('data_previsao_termino_matricula', models.CharField(max_length=20)),
                ('curso_matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mantercursos')),
                ('instituicao_matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.manterensino')),
                ('pessoa_matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.manterpessoas')),
            ],
        ),
        migrations.CreateModel(
            name='ManterFrequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_fata_frequencia', models.CharField(max_length=50)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mantercursos')),
                ('disciplina_frequencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.manterdiciplina')),
            ],
        ),
        migrations.CreateModel(
            name='ManterDisciplinaCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_disciplina_curso', models.CharField(max_length=100)),
                ('carga_horaria_disciplina_curso', models.CharField(max_length=100)),
                ('curso_disciplina_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mantercursos')),
                ('periodo_disciplina_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mantersemestres')),
            ],
        ),
        migrations.AddField(
            model_name='mantercursos',
            name='instituicao_curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.manterensino'),
        ),
        migrations.CreateModel(
            name='Avaliacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrisao', models.CharField(max_length=500)),
                ('curso_avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mantercursos')),
                ('disciplina_Avaliacoes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.manterdiciplina')),
                ('tipo_Avaliacoes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tiposavaliacoes')),
            ],
        ),
        migrations.CreateModel(
            name='Advertencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrisao_advertencia', models.CharField(max_length=500)),
                ('data_advertencia', models.CharField(max_length=50)),
                ('curso_advertencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mantercursos')),
                ('disciplina_advertencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.manterdiciplina')),
                ('pessoa_advertencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.manterpessoas')),
            ],
        ),
    ]
